### ISSUE TITLE
Observability

### ISSUE THREAD

**Issue by ralph-tice** [operatingops/python_prod_script_pattern#2]
What are your thoughts re: Logging/metrics?  I'm a little torn between introducing the standard "graphite" and Logger style here or going all-in on json-structured logs+events...

**Comment by operatingops** [comment]
Sorry for the delay @ralph-tice, I guess I don't get email notifications about new issues? Weird. There doesn't seem to be a config for it either.

I'm not actually 100% following this one, are you talking about log output format? The one I used is a little custom, and I've wondered if it shouldn't get switched to a more standard format so it's easily parsed by log collectors. Python also supports a lot more options for where to send logs that I don't support. It might be worth expanding that, as well, not everybody is going to want to rely on capturing output.

**Comment by ralph-tice** [comment]
You're way way above the average Github SLA, no worries :)

You have to "watch" the repo via https://github.com/operatingops/python_prod_script_pattern/watchers to see new issues

sorry about my brevity, I meant metrics as in timings for functions and remote calls to other APIs

and logging as in using a standard output format, yes.  I think I prefer json structure at runtime and syslog style for local development, but I don't have strong opinions for local development.

**Comment by operatingops** [comment]
Ah gotcha - I guess I assumed I was automatically 'watching' my own repos :)

I like the JSON structure, it feels better than cramming everything into a string. There's a bit in the Python docs about using [structured logs](https://docs.python.org/3/howto/logging-cookbook.html#implementing-structured-logging), but their example depends on a special function you have to remember to use. The old version of this pattern (which is gone) depended on something similar to make the simulator prefix work and it was always slightly annoying. One of the improvements in this version was to attach a filter so authors could just call getLogger and they were good to go. Even Django works that way, just call getLogger().

I also think it'd be nice to continue supporting the syslog style, I feel like there'll be folks who aren't setup to deal with JSON logs.

Maybe extract the log stuff into a separate module and provide a `structured_logger` helper function you can import? I think there's a way (although maybe a little fiddly) to use a separate formatter there so that if you use a logger from getLogger() it works the way it does today, but if you use the helper it uses a structured format. That way you can do the awesome thing but if you don't everything works like it does in other projects. Might be a bit complex but logging is hard to do right and I feel like the pattern would be more valuable if it does both for you.

On the metrics question, you mean capturing that stuff and reporting it out? Like if API calls start taking forever or script runtime gets too high? Hmmm, good question. I'd assumed you'd handle it internally and just make the script break and log errors if things got slow, but that might be because I've only used this in cases where a single timeout value was enough to tune the whole script. What do you think on this one? Maybe add more detail in the structured logs?

**Comment by operatingops** [comment]
Although, I've just now remembered that AWS CloudWatch Logs can ingest JSON and I mostly use this with AWS. That may be a good reason to default to JSON.

**Comment by ralph-tice** [comment]
Yeah, lately I am very much in favor of using JSON for the transport but specifying a schema in Protobuf for server/client code generation and payload validation.  There's some relevant open source here: https://medium.com/@tc/yes-we-serialize-as-json-over-the-wire-instead-of-protobuf-s-native-binary-format-ea61498a9b00
